console.log("Operador && - and")
console.log(2 > 1 && 2 < 5)
console.log(2 > 1 && 6 < 5)
console.log("Operador || - or")
console.log(2 > 1 || 2 < 5)
console.log(2 > 1 || 6 < 5)
console.log("Operador ! - not")
console.log(!(true && true))
console.log(!(!(true && true)))